Spring:
  #Application Properties
  application:
    name: movie-ticket-booking-system-api
    #Datasource Application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-ticket-booking-system-api?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update


